# Generated by Django 5.0.2 on 2025-04-25 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="collectionagency",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["ssn"], name="api_custome_ssn_e94c14_idx"),
        ),
    ]
