# Generated by Django 5.0.2 on 2025-04-25 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_client_id_alter_collectionagency_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="ssn",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SSN must be in format XXX-XX-XXXX",
                        regex="^\\d{3}-\\d{2}-\\d{4}$",
                    )
                ],
            ),
        ),
    ]
